

services:
  mysql:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: mydb
    ports:
      - "3306:3306"

  backend:
    build: ./backend

    ports:
      - "5050:5050"
    depends_on:
      - mysql
    volumes:  
    - ./backend/videos:/app/videos
    environment:
      DB_HOST: mysql
      DB_USER: root
      DB_PASSWORD: root
      DB_NAME: mydb

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
